### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by MingL196** [iquasere/MOSCA#10]
Hi,

I tried running MOSCA using the command:

python MOSCA/scripts/mosca.py --files /hpc/home/mzl5860/Ming_workdir/G549/MOSCA/files_rename/G549-01-R1.fastq.gz,/hpc/home/mzl5860/Ming_workdir/G549/MOSCA/files_rename/G549-01-R2.fastq.gz --output output

The program ran up the FASTQC step, but then returned the error:

Traceback (most recent call last):
  File "MOSCA/scripts/mosca.py", line 170, in <module>
    reporter.info_from_preprocessing(args.output, mg_name, mg[0])          
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/report.py", line 112, in info_from_preprocessing
    self.info_from_fastqc(output_dir, name, '[Initial quality assessment]', prefix2terms)
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/report.py", line 76, in info_from_fastqc
    prefix2terms[prefix][0], name, prefix2terms[prefix][i])) for i in [1, 2]]
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/report.py", line 76, in <listcomp>
    prefix2terms[prefix][0], name, prefix2terms[prefix][i])) for i in [1, 2]]
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/mosca_tools.py", line 584, in parse_fastqc_report
    file = open(filename).read().split('\n')
FileNotFoundError: [Errno 2] No such file or directory: 'output/Preprocess/FastQC/G549-01-R1.fastq.gz_R1_fastqc/fastqc_data.txt'

The program seems to be trying to read from the wrong file. Is there some format that the file names need to be in? 

Can this be fixed?

Thanks.

**Comment by iquasere** [comment]
Greetings! Yes, the files should end in "_R1" and "_R2", and either ".fastq.gz" or ".fastq" (MOSCA should decompress where needed). This is something that should be updated in the documentation.

**Comment by MingL196** [comment]
After renaming the files, I ran

python MOSCA/scripts/mosca.py --files /hpc/home/mzl5860/Ming_workdir/G549/MOSCA/files_rename/G549_01_S10_R1.fastq.gz,/hpc/home/mzl5860/Ming_workdir/G549/MOSCA/files_rename/G549_01_S10_R2.fastq.gz --output output -t 48

and got the error 

Traceback (most recent call last):
  File "MOSCA/scripts/mosca.py", line 270, in <module>
    assembler.run()
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/assembly.py", line 136, in run
    self.quality_control()                                                  # TODO - metaquast uses reads for sequence variation analysis - future work should involve determining the importance of that
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/assembly.py", line 118, in quality_control
    self.run_metaquast(contigs, self.out_dir + '/quality_control')
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/assembly.py", line 114, in run_metaquast
    mtools.run_command(bashCommand)
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/MOSCA/scripts/mosca_tools.py", line 192, in run_command
    subprocess.run(bashCommand.split(sep), stdout=sys.stdout, check = True)
  File "/ri/shared/modules7/miniconda3/envs/mosca-1.0.2/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['metaquast.py', '--threads', '48', '--output-dir', 'output/Assembly/Sample/quality_control', 'output/Assembly/Sample/contigs.fasta']' returned non-zero exit status 148.

Any idea what went wrong?

**Comment by iquasere** [comment]
It seems metaquast failed to start. Maybe it didn't install properly in the system? Can you please tell me what is the output of ```metaquast.py --version```?

**Comment by iquasere** [comment]
Any update on this? MOSCA 1.1 will soon be released, and will bring additional functionalities, but most important information is already obtained with MOSCA 1.0. Also, in the next days it will likely be added to the bioconda repository, facilititating its installation.

**Comment by iquasere** [comment]
MOSCA 1.1.1 can now be installed with ```conda create -n mosca -c bioconda -c conda-forge mosca``` and brings all tools automatically installed. I'll close this issue, if this problem persists don't hesitate continuing the issue.
